backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "blog"
    label: "مقالات الأكاديمية"
    folder: "blog"
    create: true
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "تاريخ النشر", name: "date", widget: "datetime"}
      - {label: "المحتوى", name: "body", widget: "markdown"}
